Update docker-build-push-dockerhub.yml

diff --git a/.github/workflows/docker-build-push-dockerhub.yml b/.github/workflows/docker-build-push-dockerhub.yml
--- a/.github/workflows/docker-build-push-dockerhub.yml
+++ b/.github/workflows/docker-build-push-dockerhub.yml
@@ -1,85 +1,50 @@
-# This is a basic workflow to help you get started with Actions
+name: Build and push image to GHCR
 
-name: Build and push image to DockerHub
-
-# Controls when the workflow will run
 on:
   push:
     branches:
       - 'main'
     tags:
       - 'v*'
-  # update on run of Update Calendso nightly submodule update
   workflow_run:
     workflows: ["Update Calendso"]
     branches: [main]
     types:
       - completed
-  # Allow running workflow manually from the Actions tab
   workflow_dispatch:
-    # Uncomment below to allow specific version workflow run
-    # inputs:
-    #   version:
-    #     description: 'Version to build'
-    #     required: true
 
-# Leaving in example for releases. Initially we simply push to 'latest'
-# on:
-  # release:
-    # types: [ created ]
+permissions:
+  contents: read
+  packages: write
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       - name: Free Disk Space (Ubuntu)
         uses: jlumbroso/free-disk-space@main
         with:
-          # Free about 4.5 GB, elminating our disk space issues
           tool-cache: true
 
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it, uncomment below
-      # - name: Checkout code at specified version
-      #   uses: actions/checkout@v2
-      #   with:
-      #     ref: ${{ github.event.inputs.version }}
-
-      - name: checkout
+      - name: Checkout code
         uses: actions/checkout@v4
-
-      - name: Git submodule update
-        run: |
-          git submodule update --init
-
-      - name: Log in to the Docker Hub registry
-        uses: docker/login-action@v3
         with:
-          # Username used to log against the Docker registry
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          # Password or personal access token used to log against the Docker registry
-          password: ${{ secrets.DOCKER_HUB_TOKEN }}
-          # Log out from the Docker registry at the end of a job
-          logout: true # optional, default is true
+          submodules: recursive
 
-      - name: Log in to the Github Container registry
+      - name: Log in to GitHub Container Registry
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Docker meta
+      - name: Docker metadata
         id: meta
         uses: docker/metadata-action@v5
         with:
           images: |
-            ghcr.io/merteraslan/cal.com
-          # Add flavor latest only on full releases, not on pre-releases
+            ghcr.io/merteraslan/calcom
           flavor: |
             latest=${{ !github.event.release.prerelease }}
 
@@ -88,15 +53,10 @@ jobs:
           grep -o '^[^#]*' .env.example > .env
           cat .env >> $GITHUB_ENV
           echo "DATABASE_HOST=localhost:5432" >> $GITHUB_ENV
-          eval $(sed -e '/^#/d' -e 's/^/export /' -e 's/$/;/' .env) ;
-
-      # Temporarily disable ARM build due to runner performance issues
-      # - name: Set up QEMU
-      #   uses: docker/setup-qemu-action@v2
+          eval $(sed -e '/^#/d' -e 's/^/export /' -e 's/$/;/' .env)
 
       - name: Start database
-        run: |
-          docker compose up -d database
+        run: docker compose up -d database
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -105,9 +65,6 @@ jobs:
             network=container:database
           buildkitd-flags: |
             --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
-#           config-inline: |
-#             [worker.oci]
-#               max-parallelism = 1
 
       - name: Build image
         id: docker_build
@@ -115,8 +72,8 @@ jobs:
         with:
           context: ./
           file: ./Dockerfile
-          load: true  # Load the image into the Docker daemon
-          push: false  # Do not push the image at this stage
+          load: true
+          push: false
           platforms: linux/amd64
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
@@ -131,8 +88,8 @@ jobs:
       - name: Test runtime
         run: |
           tags="${{ steps.meta.outputs.tags }}"
-          IFS=',' read -ra ADDR <<< "$tags"  # Convert string to array using ',' as delimiter
-          tag=${ADDR[0]}  # Get the first tag
+          IFS=',' read -ra ADDR <<< "$tags"
+          tag=${ADDR[0]}
 
           docker run --rm --network stack \
             -p 3000:3000 \
@@ -142,35 +99,26 @@ jobs:
             -e CALENDSO_ENCRYPTION_KEY=${{ env.CALENDSO_ENCRYPTION_KEY }} \
             $tag &
 
-            server_pid=$!
-
-
-            echo "Waiting for the server to start..."
-            sleep 120
-
-            echo ${{ env.NEXT_PUBLIC_WEBAPP_URL }}/auth/login
-
-            for i in {1..60}; do
-              echo "Checking server health ($i/60)..."
-              response=$(curl -o /dev/null -s -w "%{http_code}" ${{ env.NEXT_PUBLIC_WEBAPP_URL }}/auth/login)
-              echo "HTTP Status Code: $response"
-              if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
-                echo "Server is healthy"
-                # Now, shutdown the server
-                kill $server_pid
-                exit 0
-              fi
-              sleep 1
-            done
-
-            echo "Server health check failed"
-            kill $server_pid
-            exit 1
+          server_pid=$!
+          echo "Waiting for the server to start..."
+          sleep 120
+          for i in {1..60}; do
+            echo "Checking server health ($i/60)..."
+            if curl -o /dev/null -s -w "%{http_code}" ${{ env.NEXT_PUBLIC_WEBAPP_URL }}/auth/login | grep -qE '^(200|307)$'; then
+              echo "Server is healthy"
+              kill $server_pid
+              exit 0
+            fi
+            sleep 1
+          done
+          echo "Server health check failed"
+          kill $server_pid
+          exit 1
         env:
-          NEXTAUTH_SECRET: 'EI4qqDpcfdvf4A+0aQEEx8JjHxHSy4uWiZw/F32K+pA='
-          CALENDSO_ENCRYPTION_KEY: '0zfLtY99wjeLnsM7qsa8xsT+Q0oSgnOL'
+          NEXTAUTH_SECRET: ${{ env.NEXTAUTH_SECRET }}
+          CALENDSO_ENCRYPTION_KEY: ${{ env.CALENDSO_ENCRYPTION_KEY }}
 
-      - name: Push image
+      - name: Push image to GHCR
         id: docker_push
         uses: docker/build-push-action@v5
         with:
@@ -193,5 +141,4 @@ jobs:
         run: echo ${{ steps.docker_build.outputs.digest }}
 
       - name: Cleanup
-        run: |
-          docker compose down
+        run: docker compose down
